-- DEPRECATED: This migration was replaced by 013_security_fixes.sql
-- Do not run this file. It granted overly broad anonymous access to invitations.
-- If you already ran it, run 013_security_fixes.sql to revert those changes.
